export const quizData = [
  {
    title: 'Flags of Europe',
    quiz_id: 'quiz-001',
    thumbnail: 'https://placehold.co/600x400?text=Quiz+Thumbnail',
    description:
      'In this quiz, you will test your knowledge of the national flags of European countries. Challenge yourself with various levels of difficulty, and see how many of the flags you can recognize and match to their respective countries.',
    number_of_questions: 15,
    tags: ['flags', 'Europe', 'visual', 'countries'],
    difficulty_level: 2,
    average_rating: 4.3,
    date_created: '2024-10-01',
    view_count: 1240,
    author: 'GeoMaster',
    is_published: true,
    time_to_complete: 5,
    category: 'Flags',
    language: 'English',
  },
  {
    title: 'Asian Capitals Challenge',
    quiz_id: 'quiz-002',
    thumbnail: 'https://placehold.co/600x400?text=Quiz+Thumbnail',
    description:
      'This quiz will test your knowledge of the capitals of Asian countries. It includes a variety of questions that range from easy to more challenging, making it perfect for geography enthusiasts looking to sharpen their memory.',
    number_of_questions: 20,
    tags: ['capitals', 'Asia', 'intermediate', 'geography'],
    difficulty_level: 3,
    average_rating: 4.6,
    date_created: '2024-11-12',
    view_count: 980,
    author: 'Quizly',
    is_published: true,
    time_to_complete: 6,
    category: 'Capitals',
    language: 'English',
  },
  {
    title: 'African Geography Basics',
    quiz_id: 'quiz-003',
    thumbnail: 'https://placehold.co/600x400?text=Quiz+Thumbnail',
    description:
      'This beginner-level quiz focuses on identifying African countries and understanding their borders. It’s a great starting point for anyone who wants to learn more about the African continent and its diverse geography.',
    number_of_questions: 10,
    tags: ['Africa', 'beginner', 'map', 'geography basics'],
    difficulty_level: 1,
    average_rating: 4.0,
    date_created: '2025-01-05',
    view_count: 540,
    author: 'GeoLearner',
    is_published: true,
    time_to_complete: 4,
    category: 'Countries',
    language: 'English',
  },
  {
    title: 'South American Rivers',
    quiz_id: 'quiz-004',
    thumbnail: 'https://placehold.co/600x400?text=Quiz+Thumbnail',
    description:
      'Explore the major river systems of South America in this intermediate-level quiz. Test your knowledge of iconic rivers like the Amazon and Paraná, and discover the importance of these waterways to the continent’s ecosystem and people.',
    number_of_questions: 12,
    tags: ['rivers', 'South America', 'intermediate', 'nature'],
    difficulty_level: 3,
    average_rating: 3.9,
    date_created: '2024-12-10',
    view_count: 310,
    author: 'RiverNerd',
    is_published: false,
    time_to_complete: 5,
    category: 'Rivers',
    language: 'English',
  },
  {
    title: 'US State Capitals',
    quiz_id: 'quiz-005',
    thumbnail: 'https://placehold.co/600x400?text=Quiz+Thumbnail',
    description:
      'How well do you know the capitals of the 50 states in the United States? This advanced quiz will test your ability to match each state with its correct capital. Prepare for a fast-paced challenge with multiple levels of difficulty.',
    number_of_questions: 50,
    tags: ['USA', 'capitals', 'advanced', 'states'],
    difficulty_level: 4,
    average_rating: 4.7,
    date_created: '2025-02-20',
    view_count: 2230,
    author: 'MapWhiz',
    is_published: true,
    time_to_complete: 10,
    category: 'Capitals',
    language: 'English',
  },
  {
    title: 'Countries by Population',
    quiz_id: 'quiz-006',
    thumbnail: 'https://placehold.co/600x400?text=Quiz+Thumbnail',
    description:
      'This quiz challenges you to name countries based on their population statistics. It covers a wide range of nations from different continents, offering a global perspective on population distribution and trends.',
    number_of_questions: 18,
    tags: ['population', 'world', 'stats', 'demographics'],
    difficulty_level: 3,
    average_rating: 4.2,
    date_created: '2025-03-02',
    view_count: 870,
    author: 'StatGeo',
    is_published: true,
    time_to_complete: 6,
    category: 'Population',
    language: 'English',
  },
  {
    title: 'Middle East Map Challenge',
    quiz_id: 'quiz-007',
    thumbnail: 'https://placehold.co/600x400?text=Quiz+Thumbnail',
    description:
      'Can you accurately locate each country in the Middle East? This quiz offers a challenging look at the geopolitical landscape of one of the most complex regions in the world. Perfect for map enthusiasts and those interested in the Middle East’s history.',
    number_of_questions: 13,
    tags: ['Middle East', 'map', 'intermediate', 'geopolitics'],
    difficulty_level: 3,
    average_rating: 4.1,
    date_created: '2024-09-28',
    view_count: 690,
    author: 'GeoGenius',
    is_published: true,
    time_to_complete: 5,
    category: 'Maps',
    language: 'English',
  },
  {
    title: 'Oceania Flags Quiz',
    quiz_id: 'quiz-008',
    thumbnail: 'https://placehold.co/600x400?text=Quiz+Thumbnail',
    description:
      'This quiz covers the flags of countries and territories in Oceania. It’s designed for beginners who want to learn more about this beautiful region and its unique countries, offering a fun and informative challenge.',
    number_of_questions: 10,
    tags: ['flags', 'Oceania', 'beginner', 'geography'],
    difficulty_level: 2,
    average_rating: 3.8,
    date_created: '2025-04-01',
    view_count: 320,
    author: 'FlagFan',
    is_published: true,
    time_to_complete: 4,
    category: 'Flags',
    language: 'English',
  },
  {
    title: 'Landlocked Countries',
    quiz_id: 'quiz-009',
    thumbnail: 'https://placehold.co/600x400?text=Quiz+Thumbnail',
    description:
      'How many landlocked countries can you name? This advanced quiz explores countries that are completely surrounded by land, with no coastlines. It’s an interesting challenge for those curious about global geography and the logistics of landlocked nations.',
    number_of_questions: 25,
    tags: ['landlocked', 'world', 'advanced', 'countries'],
    difficulty_level: 4,
    average_rating: 4.5,
    date_created: '2025-03-18',
    view_count: 1020,
    author: 'GeoNerds',
    is_published: true,
    time_to_complete: 8,
    category: 'Countries',
    language: 'English',
  },
  {
    title: 'World Capitals Speed Round',
    quiz_id: 'quiz-010',
    thumbnail: 'https://placehold.co/600x400?text=Quiz+Thumbnail',
    description:
      'This fast-paced speed round will test how quickly you can match world capitals with their countries. It’s a timed quiz that challenges both your memory and reflexes, perfect for anyone looking to improve their capital city knowledge under pressure.',
    number_of_questions: 30,
    tags: ['capitals', 'world', 'speed', 'quiz'],
    difficulty_level: 3,
    average_rating: 4.4,
    date_created: '2025-04-12',
    view_count: 1440,
    author: 'QuizPro',
    is_published: true,
    time_to_complete: 7,
    category: 'Capitals',
    language: 'English',
  },
];
